import { AppLanguage } from './appSettings';

const copy = {
  en: {
    dashboardTitle: 'Welcome back!',
    goals: 'My Goals',
    allGoals: 'All Goals',
    active: 'Active',
    completed: 'Completed',
    quickActions: 'Quick Actions',
    addGoal: 'Add Goal',
    addSavings: 'Add Savings',
    withdraw: 'Withdraw',
    challenges: 'Challenges',
    totalSavings: 'Total Savings',
    activeGoals: 'Active Goals',
    achievements: 'Achievements',
    totalWithdrawn: 'Withdrawn',
    recentGoals: 'Recent Goals',
    recentTransactions: 'Recent Transactions',
    transactionHistory: 'Transaction History',
    createGoal: 'Create Goal',
    createGoalSubtitle: 'Add a realistic savings target to stay on track',
    targetAmount: 'Target Amount',
    currentAmount: 'Starting Amount',
    targetDate: 'Target Date',
    category: 'Category',
    description: 'Description',
    paymentMethod: 'Payment Method',
    note: 'Note',
    language: 'Language',
    english: 'English',
    bangla: 'বাংলা',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    profile: 'Profile',
    timeline: 'Timeline',
    progress: 'Progress',
    statistics: 'Statistics',
    completeDeposit: 'Complete Deposit',
    completeWithdraw: 'Complete Withdraw',
    availableBalance: 'Available balance',
    goalCompleted: 'Goal Completed!',
    goalCompletedCaption: 'This goal reached 100%. Nice work.',
    dismiss: 'Dismiss',
    goalsInProgress: 'goals in progress',
    noTransactions: 'No transactions yet',
    noGoals: 'No goals found',
    createFirstGoal: 'Create your first savings goal today',
    historyCaption: 'All your saved deposits and withdrawals are shown here.',
    switchLanguage: 'Switch Language',
    errorTitle: 'Error',
    successTitle: 'Success',
    loginErrorTitle: 'Login Error',
    registrationErrorTitle: 'Registration Error',
    registrationSuccess: 'Registration successful!',
    passwordsDoNotMatch: 'Passwords do not match',
    failedToRegister: 'Failed to register. Please try again.',
    createAccount: 'Create Account',
    joinToday: 'Join Save2Grow today',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    university: 'University',
    studentId: 'Student ID',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    register: 'Register',
    alreadyHaveAccount: 'Already have an account?',
    login: 'Login',
    selectUniversity: 'Select University',
    yourFullName: 'Your full name',
    elevenDigitPhone: '11 digit phone number',
    goalCreateValidation: 'Please fill title, target amount, and target date',
    invalidDateFormat: 'Use valid dates in YYYY-MM-DD format for target and next deposit date',
    goalCreateSuccess: 'New goal created successfully',
    goalCreateFailed: 'Goal could not be created',
    searchGoalsPlaceholder: 'Search goals, category, or description',
    allCategories: 'All',
    latest: 'Latest',
    topProgress: 'Top Progress',
    deadline: 'Deadline',
    topTarget: 'Top Target',
    invest: 'Invest',
    travel: 'Travel',
    study: 'Study',
    emergency: 'Emergency',
    daily: 'Daily',
    every3Days: 'Every 3 Days',
    every7Days: 'Every 7 Days',
    monthly: 'Monthly',
    every3Months: 'Every 3 Months',
    nextDepositDate: 'Next Deposit Date',
    depositFrequency: 'Deposit Frequency',
    startupFund: 'Startup Fund',
    whatSavingFor: 'What are you saving for?',
    notifications: 'Notifications',
    notificationsCaption: 'Recent milestones, reminders, and challenge updates are shown here.',
    noNotificationsYet: 'No notifications yet',
    notificationsEmptyCaption: 'When you save, withdraw, or join challenges, updates will appear here.',
    transactionDetails: 'Transaction Details',
    close: 'Close',
    moneyIn: 'Money In',
    moneyOut: 'Money Out',
    searchTransactions: 'Search transactions',
    deposits: 'Deposits',
    withdrawals: 'Withdrawals',
    historyEmptyCaption: 'Add savings or withdraw from a goal to see activity here.',
    monthlyReport: 'Monthly Report',
    monthlyReportCaption: "This month's saving pulse, withdrawal activity, and top performing goal.",
    depositsLabel: 'Deposits',
    withdrawalsLabel: 'Withdrawals',
    netSavings: 'Net Savings',
    transactionsLabel: 'Transactions',
    weeklyDepositTrend: 'Weekly Deposit Trend',
    bestGoalThisMonth: 'Best Goal This Month',
    noGoalsForReport: 'No goals available for this report yet.',
    goalCategoryAnalytics: 'Goal Category Analytics',
    insights: 'Insights',
    savingPace: 'Saving pace',
    positiveSavingsInsight: 'You are growing savings positively this month. Keep the same momentum.',
    negativeSavingsInsight: 'Withdrawals are ahead this month. A few new deposits will balance things again.',
    recommendedNextStep: 'Recommended next step',
    recommendedNextStepText: 'Focus on your strongest goal and add one more deposit this week to keep progress visible.',
    achievementsCaption: 'Track earned badges from goals, transactions, and challenge activity.',
    unlockedBadges: 'Unlocked badges',
    completedGoalsLabel: 'Completed goals',
    joinedChallengesLabel: 'Joined challenges',
    unlocked: 'Unlocked',
    locked: 'Locked',
    achievementFirstSaver: 'First Saver',
    achievementFirstSaverDesc: 'Completed your first deposit in the app.',
    achievementSteadySaver: 'Steady Saver',
    achievementSteadySaverDesc: 'Made at least 3 deposits toward your goals.',
    achievementGoalFinisher: 'Goal Finisher',
    achievementGoalFinisherDesc: 'Completed at least one savings goal.',
    achievementChallengePlayer: 'Challenge Player',
    achievementChallengePlayerDesc: 'Joined your first community challenge.',
    achievementSmartWithdraw: 'Smart Withdraw',
    achievementSmartWithdrawDesc: 'Recorded a withdrawal and kept your tracking balanced.',
    achievementSavingsHero: 'Savings Hero',
    achievementSavingsHeroDesc: 'Reached Tk 50,000 in total savings.',
    challengeNotFound: 'Challenge not found',
    challengeNotFoundCaption: 'This challenge is no longer available.',
    reward: 'Reward',
    ends: 'Ends',
    participants: 'Participants',
    target: 'Target',
    challengeProgress: 'Progress',
    challengeSnapshot: 'Challenge Snapshot',
    joinedStatus: 'Joined status',
    alreadyJoined: 'Already joined',
    notJoinedYet: 'Not joined yet',
    type: 'Type',
    bestNextStep: 'Best next step',
    depositDays: 'Deposit days',
    bestGoalProgress: 'Best goal progress',
    savedSoFar: 'Saved so far',
    communityReadySavings: 'Community-ready savings',
    totalSavingsGoalsCaption: 'Based on your current total savings across all goals.',
    depositDaysCaption: 'Counts your completed deposit activities in your history.',
    bestGoalProgressCaption: 'Tracks the highest completion percentage among your goals.',
    communityReadySavingsCaption: 'Uses your current saved amount as your contribution snapshot.',
    saveDaysNextStep: 'Make regular deposits to increase streak progress.',
    defaultChallengeNextStep: 'Keep adding savings to move closer to the target.',
    leaderboard: 'Leaderboard',
    yourRank: 'Your rank',
    youAlreadyJoinedChallenge: 'You already joined this challenge',
    joinedChallengePrefix: 'Joined',
    joinFailed: 'Join Failed',
    challengeCouldNotJoin: 'This challenge could not be joined right now.',
    joinThisChallenge: 'Join this challenge',
    youAlreadyJoined: 'You already joined',
    logoutTitle: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    languageUpdated: 'Language updated',
    languageUpdateFailed: 'Could not update language',
    fieldCannotBeEmpty: 'Field cannot be empty',
    profileUpdated: 'Profile updated',
    emailUpdated: 'Email updated',
    phoneUpdated: 'Phone updated',
    profileUpdateFailed: 'Could not update profile',
    reset: 'Reset',
    helpFaq: 'Help & FAQ',
    helpFaqBody: '1. How do I add savings?\nOpen any goal and tap Add Savings.\n\n2. How do I withdraw?\nOpen a goal and tap Withdraw, then enter amount and method.\n\n3. Is my data saved?\nYes. Deposits, withdrawals, goals, and profile edits are saved to your account.\n\n4. Registration not working?\nUse a valid email, 11-digit phone number, and password with at least 6 characters.',
    aboutSave2Grow: 'About Save2Grow',
    aboutSave2GrowBody: 'Save2Grow is a student-focused savings app designed to help users create goals, track deposits, manage withdrawals, and build better money habits.\n\nMain features:\n• Goal creation and tracking\n• Deposit and withdraw history\n• Challenge participation\n• Profile editing\n\nVersion: 1.0.0',
    monthlyDepositsOverview: 'Monthly deposits overview',
    account: 'Account',
    support: 'Support',
    editProfile: 'Edit Profile',
    emailSettings: 'Email Settings',
    reminderSettings: 'Reminder Settings',
    chooseReminderCaption: 'Choose reminder frequency and preferred savings time.',
    transactionTypeDeposit: 'Deposit',
    transactionTypeWithdraw: 'Withdraw',
    youLabel: 'You',
    studentFallback: 'Student',
    savingsMotto: 'Grow small savings into big wins',
    savingsMomentumCaption: 'Track your savings momentum across goals and recent deposits.',
    monthlyDepositTrend: 'Monthly deposit trend',
    seeAll: 'See All',
    loginToAccount: 'Login to your account',
    noAccountYet: "Don't have an account?",
    remindersUpdated: 'Reminder settings updated',
    remindersUpdateFailed: 'Could not update reminder settings',
    savingsReminders: 'Savings reminders',
    remindersToggleCaption: 'Turn reminders on or off from one place.',
    frequency: 'Frequency',
    preferredTime: 'Preferred time',
    reminderMorningCaption: 'Morning motivation before your day begins.',
    reminderEveningCaption: 'A calm evening reminder to review your goals.',
    reminderLateCaption: 'A late-evening check-in before wrapping up the day.',
  },
  bn: {
    dashboardTitle: 'আবার স্বাগতম!',
    goals: 'আমার গোল',
    allGoals: 'সব গোল',
    active: 'চলমান',
    completed: 'সম্পন্ন',
    quickActions: 'দ্রুত কাজ',
    addGoal: 'গোল যোগ',
    addSavings: 'সেভিংস যোগ',
    withdraw: 'উইথড্র',
    challenges: 'চ্যালেঞ্জ',
    totalSavings: 'মোট সেভিংস',
    activeGoals: 'চলমান গোল',
    achievements: 'অর্জন',
    totalWithdrawn: 'মোট উত্তোলন',
    recentGoals: 'সাম্প্রতিক গোল',
    recentTransactions: 'সাম্প্রতিক ট্রানজ্যাকশন',
    transactionHistory: 'ট্রানজ্যাকশন হিস্ট্রি',
    createGoal: 'নতুন গোল',
    createGoalSubtitle: 'ট্র্যাকে থাকতে একটি বাস্তব savings target যোগ করো',
    targetAmount: 'টার্গেট এমাউন্ট',
    currentAmount: 'শুরুর এমাউন্ট',
    targetDate: 'টার্গেট তারিখ',
    category: 'ক্যাটাগরি',
    description: 'বিবরণ',
    paymentMethod: 'পেমেন্ট মেথড',
    note: 'নোট',
    language: 'ভাষা',
    english: 'English',
    bangla: 'বাংলা',
    saveChanges: 'সেভ করো',
    cancel: 'বাতিল',
    profile: 'প্রোফাইল',
    timeline: 'টাইমলাইন',
    progress: 'অগ্রগতি',
    statistics: 'পরিসংখ্যান',
    completeDeposit: 'ডিপোজিট সম্পন্ন',
    completeWithdraw: 'উইথড্র সম্পন্ন',
    availableBalance: 'উপলভ্য ব্যালেন্স',
    goalCompleted: 'গোল সম্পন্ন!',
    goalCompletedCaption: 'এই goal 100% হয়েছে। দারুণ কাজ।',
    dismiss: 'বন্ধ করো',
    goalsInProgress: 'টি goal চলছে',
    noTransactions: 'এখনও কোনো ট্রানজ্যাকশন নেই',
    noGoals: 'কোনো goal পাওয়া যায়নি',
    createFirstGoal: 'আজই তোমার প্রথম savings goal তৈরি করো',
    historyCaption: 'তোমার সব saved deposit আর withdraw এখানে দেখাবে।',
    switchLanguage: 'ভাষা বদলাও',
    errorTitle: 'এরর',
    successTitle: 'সফল',
    loginErrorTitle: 'লগইন এরর',
    registrationErrorTitle: 'রেজিস্ট্রেশন এরর',
    registrationSuccess: 'রেজিস্ট্রেশন সফল হয়েছে!',
    passwordsDoNotMatch: 'পাসওয়ার্ড মিলছে না',
    failedToRegister: 'রেজিস্ট্রেশন করা যায়নি। আবার চেষ্টা করো।',
    createAccount: 'অ্যাকাউন্ট তৈরি করো',
    joinToday: 'আজই Save2Grow-এ যোগ দাও',
    fullName: 'পূর্ণ নাম',
    phoneNumber: 'ফোন নাম্বার',
    university: 'বিশ্ববিদ্যালয়',
    studentId: 'স্টুডেন্ট আইডি',
    password: 'পাসওয়ার্ড',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করো',
    register: 'রেজিস্টার',
    alreadyHaveAccount: 'আগে থেকেই অ্যাকাউন্ট আছে?',
    login: 'লগইন',
    selectUniversity: 'বিশ্ববিদ্যালয় বেছে নাও',
    yourFullName: 'তোমার পুরো নাম',
    elevenDigitPhone: '১১ সংখ্যার ফোন নাম্বার',
    goalCreateValidation: 'টাইটেল, টার্গেট এমাউন্ট আর টার্গেট তারিখ দাও',
    invalidDateFormat: 'টার্গেট আর নেক্সট ডিপোজিট ডেট YYYY-MM-DD ফরম্যাটে দাও',
    goalCreateSuccess: 'নতুন গোল সফলভাবে তৈরি হয়েছে',
    goalCreateFailed: 'গোল তৈরি করা যায়নি',
    searchGoalsPlaceholder: 'গোল, ক্যাটাগরি বা বিবরণ খুঁজো',
    allCategories: 'সব',
    latest: 'নতুন',
    topProgress: 'সেরা অগ্রগতি',
    deadline: 'ডেডলাইন',
    topTarget: 'বড় টার্গেট',
    invest: 'ইনভেস্ট',
    travel: 'ট্রাভেল',
    study: 'স্টাডি',
    emergency: 'জরুরি',
    daily: 'প্রতিদিন',
    every3Days: '৩ দিন পর পর',
    every7Days: '৭ দিন পর পর',
    monthly: 'মাসিক',
    every3Months: '৩ মাস পর পর',
    nextDepositDate: 'পরের ডিপোজিট তারিখ',
    depositFrequency: 'ডিপোজিট ফ্রিকোয়েন্সি',
    startupFund: 'স্টার্টআপ ফান্ড',
    whatSavingFor: 'কি জন্য সেভ করছ?',
    notifications: 'নোটিফিকেশন',
    notificationsCaption: 'সাম্প্রতিক milestone, reminder আর challenge update এখানে দেখাবে।',
    noNotificationsYet: 'এখনও কোনো নোটিফিকেশন নেই',
    notificationsEmptyCaption: 'সেভ, উইথড্র বা চ্যালেঞ্জে join করলে update এখানে আসবে।',
    transactionDetails: 'ট্রানজ্যাকশন বিস্তারিত',
    close: 'বন্ধ',
    moneyIn: 'জমা',
    moneyOut: 'খরচ',
    searchTransactions: 'ট্রানজ্যাকশন খুঁজো',
    deposits: 'ডিপোজিট',
    withdrawals: 'উইথড্র',
    historyEmptyCaption: 'কোনো goal-এ সেভ বা উইথড্র করলে activity এখানে দেখাবে।',
    monthlyReport: 'মাসিক রিপোর্ট',
    monthlyReportCaption: 'এই মাসের সেভিংস, উইথড্র activity আর সেরা goal এখানে দেখাবে।',
    depositsLabel: 'ডিপোজিট',
    withdrawalsLabel: 'উইথড্র',
    netSavings: 'নেট সেভিংস',
    transactionsLabel: 'ট্রানজ্যাকশন',
    weeklyDepositTrend: 'সাপ্তাহিক ডিপোজিট ট্রেন্ড',
    bestGoalThisMonth: 'এই মাসের সেরা goal',
    noGoalsForReport: 'এই রিপোর্টের জন্য এখনও কোনো goal নেই।',
    goalCategoryAnalytics: 'ক্যাটাগরি অ্যানালিটিক্স',
    insights: 'ইনসাইট',
    savingPace: 'সেভিংস গতি',
    positiveSavingsInsight: 'এই মাসে তোমার সেভিংস ভালোভাবে বাড়ছে। একইভাবে চালিয়ে যাও।',
    negativeSavingsInsight: 'এই মাসে উইথড্র একটু বেশি হয়েছে। আরেকটু ডিপোজিট দিলে balance হবে।',
    recommendedNextStep: 'পরের best step',
    recommendedNextStepText: 'সবচেয়ে ভালো goal-এ এই সপ্তাহে আরেকটা deposit দিলে progress আরও visible হবে।',
    achievementsCaption: 'গোল, ট্রানজ্যাকশন আর চ্যালেঞ্জ activity থেকে অর্জিত badge এখানে দেখো।',
    unlockedBadges: 'আনলকড ব্যাজ',
    completedGoalsLabel: 'সম্পন্ন goal',
    joinedChallengesLabel: 'জয়েন করা চ্যালেঞ্জ',
    unlocked: 'আনলকড',
    locked: 'লকড',
    achievementFirstSaver: 'প্রথম সেভার',
    achievementFirstSaverDesc: 'অ্যাপে প্রথম deposit সম্পন্ন করেছ।',
    achievementSteadySaver: 'নিয়মিত সেভার',
    achievementSteadySaverDesc: 'কমপক্ষে ৩টি deposit করেছ।',
    achievementGoalFinisher: 'গোল ফিনিশার',
    achievementGoalFinisherDesc: 'কমপক্ষে একটি savings goal সম্পন্ন করেছ।',
    achievementChallengePlayer: 'চ্যালেঞ্জ প্লেয়ার',
    achievementChallengePlayerDesc: 'প্রথম community challenge-এ join করেছ।',
    achievementSmartWithdraw: 'স্মার্ট উইথড্র',
    achievementSmartWithdrawDesc: 'একটি withdrawal record করে tracking balanced রেখেছ।',
    achievementSavingsHero: 'সেভিংস হিরো',
    achievementSavingsHeroDesc: 'মোট savings Tk 50,000 এ পৌঁছেছে।',
    challengeNotFound: 'চ্যালেঞ্জ পাওয়া যায়নি',
    challengeNotFoundCaption: 'এই চ্যালেঞ্জটি আর উপলব্ধ নেই।',
    reward: 'রিওয়ার্ড',
    ends: 'শেষ হবে',
    participants: 'অংশগ্রহণকারী',
    target: 'টার্গেট',
    challengeProgress: 'অগ্রগতি',
    challengeSnapshot: 'চ্যালেঞ্জ স্ন্যাপশট',
    joinedStatus: 'জয়েন স্ট্যাটাস',
    alreadyJoined: 'আগেই জয়েন করা',
    notJoinedYet: 'এখনও জয়েন করা হয়নি',
    type: 'ধরণ',
    bestNextStep: 'পরের best step',
    depositDays: 'ডিপোজিট দিন',
    bestGoalProgress: 'সেরা goal progress',
    savedSoFar: 'এখন পর্যন্ত সেভ',
    communityReadySavings: 'কমিউনিটি-ready savings',
    totalSavingsGoalsCaption: 'সব goal মিলিয়ে তোমার current savings থেকে হিসাব করা হয়েছে।',
    depositDaysCaption: 'তোমার history-র completed deposit activity count করে।',
    bestGoalProgressCaption: 'তোমার goal-গুলোর মধ্যে সবচেয়ে বেশি completion percentage track করে।',
    communityReadySavingsCaption: 'তোমার current saved amount contribution snapshot হিসেবে ব্যবহার করে।',
    saveDaysNextStep: 'নিয়মিত deposit করলে streak progress বাড়বে।',
    defaultChallengeNextStep: 'আরও savings যোগ করলে target-এর দিকে এগোবে।',
    leaderboard: 'লিডারবোর্ড',
    yourRank: 'তোমার র্যাঙ্ক',
    youAlreadyJoinedChallenge: 'তুমি এই চ্যালেঞ্জে আগেই join করেছ',
    joinedChallengePrefix: 'জয়েন করেছ',
    joinFailed: 'জয়েন ব্যর্থ',
    challengeCouldNotJoin: 'এই মুহূর্তে চ্যালেঞ্জে join করা যাচ্ছে না।',
    joinThisChallenge: 'এই চ্যালেঞ্জে জয়েন করো',
    youAlreadyJoined: 'তুমি আগেই join করেছ',
    logoutTitle: 'লগআউট',
    logoutConfirm: 'তুমি কি লগআউট করতে চাও?',
    languageUpdated: 'ভাষা আপডেট হয়েছে',
    languageUpdateFailed: 'ভাষা আপডেট করা যায়নি',
    fieldCannotBeEmpty: 'ফিল্ড খালি রাখা যাবে না',
    profileUpdated: 'প্রোফাইল আপডেট হয়েছে',
    emailUpdated: 'ইমেইল আপডেট হয়েছে',
    phoneUpdated: 'ফোন আপডেট হয়েছে',
    profileUpdateFailed: 'প্রোফাইল আপডেট করা যায়নি',
    reset: 'রিসেট',
    helpFaq: 'হেল্প ও FAQ',
    helpFaqBody: '1. কীভাবে savings add করবো?\nযেকোনো goal open করে Add Savings চাপো।\n\n2. কীভাবে withdraw করবো?\nGoal open করে Withdraw চাপো, তারপর amount আর method দাও।\n\n3. Data save থাকবে?\nহ্যাঁ। Deposit, withdrawal, goals আর profile edits তোমার account-এ save থাকবে।\n\n4. Registration কাজ না করলে?\nValid email, ১১ সংখ্যার phone number, আর কমপক্ষে ৬ অক্ষরের password ব্যবহার করো।',
    aboutSave2Grow: 'Save2Grow সম্পর্কে',
    aboutSave2GrowBody: 'Save2Grow একটি student-focused savings app, যা users-দের goal create, deposit track, withdrawal manage, আর better money habits build করতে সাহায্য করে.\n\nমূল feature:\n• Goal creation and tracking\n• Deposit and withdraw history\n• Challenge participation\n• Profile editing\n\nVersion: 1.0.0',
    monthlyDepositsOverview: 'মাসভিত্তিক ডিপোজিট overview',
    account: 'অ্যাকাউন্ট',
    support: 'সাপোর্ট',
    editProfile: 'প্রোফাইল এডিট',
    emailSettings: 'ইমেইল সেটিংস',
    reminderSettings: 'রিমাইন্ডার সেটিংস',
    chooseReminderCaption: 'রিমাইন্ডারের সময় আর frequency বেছে নাও।',
    transactionTypeDeposit: 'ডিপোজিট',
    transactionTypeWithdraw: 'উইথড্র',
    youLabel: 'তুমি',
    studentFallback: 'স্টুডেন্ট',
    savingsMotto: 'ছোট সেভিংস থেকে বড় সাফল্য তৈরি করো',
    savingsMomentumCaption: 'goal আর recent deposit জুড়ে তোমার savings momentum track করো।',
    monthlyDepositTrend: 'মাসিক ডিপোজিট ট্রেন্ড',
    seeAll: 'সব দেখো',
    loginToAccount: 'তোমার অ্যাকাউন্টে লগইন করো',
    noAccountYet: 'এখনও অ্যাকাউন্ট নেই?',
    remindersUpdated: 'রিমাইন্ডার সেটিংস আপডেট হয়েছে',
    remindersUpdateFailed: 'রিমাইন্ডার সেটিংস আপডেট করা যায়নি',
    savingsReminders: 'সেভিংস রিমাইন্ডার',
    remindersToggleCaption: 'এক জায়গা থেকে reminders চালু বা বন্ধ করো।',
    frequency: 'ফ্রিকোয়েন্সি',
    preferredTime: 'পছন্দের সময়',
    reminderMorningCaption: 'দিন শুরু হওয়ার আগে সকালের motivation।',
    reminderEveningCaption: 'সন্ধ্যায় goal review করার শান্ত reminder।',
    reminderLateCaption: 'দিন শেষ করার আগে late-evening check-in।',
  },
};

export const getCopy = (language: AppLanguage = 'en') => {
  return copy[language] || copy.en;
};
